name: Pull Request Check
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - .gitignore
env:
  GO_VERSION: 1.15.5
jobs:
  build:
    name: 'Build on ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-18.04" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Setup Go ${{ env.GO_VERSION }}'
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: 'Check out project files'
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 'Prepare environment'
        run: |
          # https://github.com/actions/virtual-environments/issues/798
          sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: 'Build'
        run: |
          make build
  golangci:
    strategy:
      matrix:
        go-version: [ 1.15.x ]
        os: [ "ubuntu-18.04" ]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.36.0

